/*
 * This file was manually constructed to look like a test generated by EvoSuite.
 */


import org.junit.Test;
import static org.junit.Assert.*;

public class FailingPatterns_ESTest {

    @Test(timeout = 4000)
    public void test0()  throws Throwable  {
        boolean result = Patterns.pattern0(35);

        assertEquals(42, result);
    }
}
