/*
 * This file was manually constructed to look like a patterns class generated by Schaapi.
 *
 * This file is just used for the creation of the corresponding .class file, this .java file is not used by Schaapi.
 */

import org.cafejojo.dummysimplemavenlibrary.Calculator;

public class Patterns {
    public static int pattern0(int a) {
        Calculator calculator = new Calculator();

        int sum = calculator.sum(a, 5);

        return calculator.sum(sum, 2);
    }
}
